#!/usr/bin/env sh
readonly __ENTRY=$(basename "$0")
# shellcheck source=../../lib/log-helpers.sh
. "$ANYCI_ROOT/lib/log-helpers.sh"

log "debug step called. dumping the environment!"
env | sort | sed 's/^/    /g'
