#!/usr/bin/env sh
readonly __ENTRY=$(basename "$0")
# shellcheck source=../../lib/log-helpers.sh
. "$ANYCI_ROOT/lib/log-helpers.sh"

__ll=WARN log "default $ANYCI_STEP_NAME step called, although has not yet been implemented..." \
  "please implement!"
