#!/usr/bin/env bash
set -eo pipefail
# shellcheck source=../../lib/log-helpers.sh
. "$ANYCI_ROOT/lib/log-helpers.sh"
# shellcheck source=../../lib/step-helpers.sh
. "$ANYCI_ROOT/lib/step-helpers.sh"
# shellcheck source=../../lib/compose-helpers.sh
. "$ANYCI_ROOT/lib/compose-helpers.sh"

compose_flags+=(
  -f "ci/docker-compose.yml"
)

log "building ci/docker-compose.yml"
DOCKER_BUILDKIT=1 compose build --pull

log "writing build.manifest"
compose config | yq -r '.services[] | .image' > "$PIPELINE_ARTIFACTS/build.manifest"

log "BUILD_MANIFEST:"
sort < "$PIPELINE_ARTIFACTS/build.manifest" | sed "s/^/#    /g"
