#!/usr/bin/env sh
set -eo pipefail

# shellcheck source=../../lib/log-helpers.sh
. "$ANYCI_ROOT/lib/log-helpers.sh"
# shellcheck source=../../lib/step-helpers.sh
. "$ANYCI_ROOT/lib/step-helpers.sh"

log "debug step called. dumping the environment!"
env | sort | sed 's/^/    /g'
