#!/usr/bin/env sh
readonly __entry=$(basename "$0")
log(){ printf "%-19s [${LOG_LEVEL:-INFO}] $*\n" "# ($__entry)" >&2; }
die(){ LOG_LEVEL=ERR log "$*"; exit 1; }

log "default $ANYCI_STEP_NAME step called, although has not yet been implemented..." \
  "\nplease implement!"
